name: echo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  firebase_core: ^4.7.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/onboarding/
    - assets/splash/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    background_color: "#000000"
  image_path: "assets/icon/echo.png"
  adaptive_icon_background: "assets/icon/echo_background.png"  # For Android adaptive icons
  adaptive_icon_foreground: "assets/icon/echo_foreground.png"  # For Android adaptive icons


flutter_native_splash:
  # Platform enable/disable
  android: true
  ios: true
  web: true
  image: assets/splash/echosplashicon.png
  color: "#02091A"


  # Web specific
  web_image_mode: center  # Options: center, contain, cover, stretch