name: hi_gemma
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  google_generative_ai: ^0.4.7
  provider: ^6.0.0
  http: ^1.1.0
  firebase_core: ^2.24.0
  cloud_firestore: ^4.12.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.6.0
  firebase_auth: ^4.10.0
  audioplayers: ^5.1.0
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
